export const articlesArray = [
  {
    title:
      'Trump’s Strategy: Make ‘Wobbly Republicans’ Think Their Party Is Great Again',
    text:
      'President Trump and his party are entering the nine-week stretch until Election Day with their success riding on a hope that enough voters come to the following conclusion: You’re not as bad as we thought.  As part of this strategy, Republicans and the Trump campaign are attempting to focus voters’ minds away from the pandemic and economic crisis and on a narrower set of cultural issues. For example, the nation is in dire straits, they say, not because of Covid-19 deaths or double-digit unemployment or racial discord, but because of liberals who want to “cancel” conservatives, criminals who are rampaging from the cities into white suburbs and a Democratic presidential ticket that is a “Trojan horse” for Fidel Castro-style authoritarianism.  These topics often consume conservative media, are already appearing in ads from the Trump campaign and his allies — and were mentioned repeatedly over the four nights of the Republican National Convention.  To complement the drumbeat of panic about the radical left,  convention speakers stressed their personal experiences with the president and shared affirmations about his character — a man of “deep compassion” and “endless kindness” with an “exceptional work ethic,” they said. And they attempted to refute the idea that he dislikes Black people, women and immigrants, calling those divisive characterizations by the left and distortions of a media “fog machine.” Ben Carson, the only Black member of Mr. Trump’s cabinet, said people who called the president racist “could not be more wrong.”  Strategists in both parties say this attempt to reframe the country’s understanding of who the president is could backfire, coming off as dismissive of the acute racial awareness that has been leading people of all political beliefs and races to re-examine their attitudes about discrimination.  But they also said it just might work.  “It is a fascinating tightrope they’re walking on because on the one hand Trump is saying some of the most racist, bombastic stuff ever to come out of the mouth of a nominee of a major political party,” said Cornell Belcher, a Democratic pollster who worked for Barack Obama’s two presidential campaigns, when racial attitudes were never far from the surface. “At the same time, they are professing and having others validate that he is not a racist. The contradiction is mind boggling.”',
    date: '29-Aug-2020',
    imgURL:
      'https://d279m997dpfwgl.cloudfront.net/wp/2019/07/AP_19201004713022-1000x667.jpg',
  },
  {
    title: 'When It Comes to Covid-19, Most of Us Have Risk Exactly Backward',
    text:
      'My daughter argues that as long as she’s seeing all of her friends together in school, they should be able to gather together in their houses as well. Unfortunately, she has risk exactly backward. She’s not alone; lots of Americans do.  My kids, like most in Indiana, have been back at school since mid-August. Each time my 9th and 11th grader head off to high school, they spend more time among other human beings in a day than they had cumulatively all summer. Because of that, they along with many of their friends and those friends’ parents think that there’s less reason to be careful in other aspects of their lives.  But as we loosen restrictions in some areas, we should be increasing restrictions in others. If kids are going to take on more risk at school, they should find ways to be even safer outside of it. Large groupings at a friend’s house are not a good idea.  Too many view protective measures as all or nothing: Either we do everything, or we might as well do none. That’s wrong. Instead, we need to see that all our behavior adds up.',
    date: '29-Aug-2020',
    imgURL:
      'https://directorsblog.nih.gov/wp-content/uploads/2020/03/COVID-19-Card-3.jpg',
  },
  {
    title:
      'One Person Dead in Portland After Clashes Between Trump Supporters and Protesters',
    text:
      'A man affiliated with a right-wing group was shot and killed Saturday as a large group of supporters of President Trump traveled in a caravan through downtown Portland, Ore., which has had nightly protests for three consecutive months. The pro-Trump rally drew hundreds of trucks full of supporters into the city. At times, Trump supporters and counterprotesters clashed on the streets, with people shooting paintball guns from the beds of pickup trucks and protesters throwing objects back at them. A video that purports to be of the shooting, taken from the far side of the street, showed a small group of people in the road outside what appears to be a parking garage. Gunfire erupts, and a man collapses in the street. The man who was shot and killed was wearing a hat with the insignia of Patriot Prayer, a far-right group based in the Portland area that has clashed with protesters in the past. Joey Gibson, the head of the group, said Sunday he could not share many details but could confirm the man was a good friend and supporter of Patriot Prayer.',
    date: '30-Aug-2020',
    imgURL:
      'https://s.abcnews.com/images/Politics/WireAP_beb642bf43a94480872f08bec96afb00_16x9_992.jpg',
  },

  {
    title:
      'Covid-19 case fatality dips to 1.79%, active cases cross 765,000 in India',
    text:
      'India reported around 78,000 new coronavirus disease (Covid-19) cases, as the number of active viral infection cases climbed to 7,65,302 until Saturday night, according to the data shared by the Union Ministry of Health and Family Welfare (MoH&FW). With 65,000 recoveries, 77% people diagnosed with Covid-19 have recovered from their viral infection during the same period. So far, 2.7 million Indians have recovered from their viral infection. Maharashtra is still the epicentre of Covid-19 pandemic in the country, as it reported 16,286 new cases on Saturday. While Andhra Pradesh (AP) and Karnataka reported 10,548 and 8,324 new Covid-19 cases, respectively, the data collated by HT showed. The Centre has credited the effective implementation of its testing, tracking and treating policy for the high recovery of Covid-19 cases. Click here for full Covid-19 coverage. India has been focussing on increasing the daily testing of swab samples. Around 1.5 million swab samples being tested in the last 24 hours. Tracking and timely surveillance of close contacts and effectively treating those with the viral infection through widening medical infrastructure has increased the recovery rate, the ministry said. The ministry has attributed the low case fatality rate (CFR) of 1.79% until Saturday to the effective and timely clinical management of Covid-19 cases. In a meeting of the Group of Ministers (GoMs) on Saturday, Union Minister for Health & Family Welfare Dr Harsh Vardhan said that India has been able to keep the CFR much lower than many countries, despite resource constraints.',
    date: '30-Aug-2020',
    imgURL:
      'https://www.hindustantimes.com/rf/image_size_960x540/HT/p2/2020/08/31/Pictures/virus-outbreak-india_1249f602-eaf2-11ea-98f7-bd84aa0e920b.jpg',
  },
  {
    title:
      'IPL 2020: Suresh Raina pulls out, CSK’s worries grow as players become wary',
    text:
      'Chennai Super Kings’ Suresh Raina pulled out of the Indian Premier League (IPL) citing ‘personal reasons’ on Saturday as BCCI confirmed that 13 personnel, including two players, had tested positive for Covid-19. Reports said the former India batsman’s uncle died and aunt is in serious condition following an attack on them 10 days ago in their home near Pathankot. The player or CSK did not confirm whether the incident was behind Raina flying home. Raina is the first to drop out of this year’s edition, being held in the UAE from September 19-November 10 due to the Covid-19 situation in India, but may not be the last, league sources said. “Suresh Raina has returned to India for personal reasons and will be unavailable for the remainder of the IPL season. Chennai Super Kings offers complete support to Suresh and his family during this time,” CSK CEO, KS Viswanathan, tweeted. “Senior spinner Harbhajan Singh who is in India and did not take part in CSK’s preparatory camp in Chennai (Aug 15-20) is worried whether to participate in the tournament or not,” a source close to the player said. He is expected to join the team in the UAE on Tuesday. Many players, mostly foreigners, are yet to join their teams in the UAE, and some among them are bound to be in a dilemma like Harbhajan whether or not to play amid the pandemic. The league was first postponed from April-May and then shifted out of India. Also read: Suresh Raina’s relative dies in attack by robbers, four sustain injuries BCCI said: “(A) total of 1,988 RT-PCR COVID tests were carried out between August 20—28 across all participant groups in the UAE. These groups include players, support staff, team management, BCCI staff, IPL operational team, hotel and ground transport staff…. All the affected personnel and their close contacts are asymptomatic and have been isolated from other team members. They are being monitored by the IPL medical team.” All those who have tested positive are said to be from CSK with India pacer Deepak Chahar and Ruturaj Gaikwad—a prolific India A batsman from Pune—the two players among them, an official said. The quarantine period for the team that reached Dubai on Aug 21 should have ended on Friday, but is expected to be extended. All may have to test negative for the team to enter the bio-bubble and start training.',
    date: '30-Aug-2020',
    imgURL:
      'https://www.hindustantimes.com/rf/image_size_960x540/HT/p2/2020/08/30/Pictures/_35f25162-ea66-11ea-b931-a708c0ef05a7.jpg',
  },
];
